29 márc. 2021 11:36:05,452 [MANDATORY]  - [AIS]             Initiating EnterpriseOne startup using configuration location (default_path) as 'C:\jde_home\SCFHA\targets\AIS_DV91\config'. 
29 márc. 2021 11:36:06,036 [MANDATORY]  - [AIS]             Successfully set the targetType to restserver 
29 márc. 2021 11:36:06,076 [MANDATORY]  - [AIS]             Successfully Initialize the management infrastructure com.oracle.e1.rest.E1RestSysInfoBean@4c5a460b 
29 márc. 2021 11:36:06,088 [MANDATORY]  - [AIS]             Successfully register the runtime metric used by SCF to handle the logging configuration dynamically com.jdedwards.base.logging.saw.JdeSawManager@5b71e026 
29 márc. 2021 11:36:06,089 [MANDATORY]  - [AIS]             Successfully got the Management Server Singleton and Registered sys_info and saw_log_manager 
29 márc. 2021 11:36:06,090 [MANDATORY]  - [AIS]             Obtained resUrl1 to be /C:/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/servers/AIS-DV91/stage/AIS_DV91/app/JDERestProxy.war/WEB-INF/classes/com/oracle/e1/rest/mbeans-descriptors.xml 
29 márc. 2021 11:36:06,090 [MANDATORY]  - [AIS]             Obtained resUrl2 to be /C:/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/servers/AIS-DV91/stage/AIS_DV91/app/JDERestProxy.war/WEB-INF/classes/com/oracle/e1/jdemf/mbeans-descriptors.xml 
29 márc. 2021 11:36:06,095 [MANDATORY]  - [AIS]             Successfully loaded the descriptor at /C:/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/servers/AIS-DV91/stage/AIS_DV91/app/JDERestProxy.war/WEB-INF/classes/com/oracle/e1/rest/mbeans-descriptors.xml 
29 márc. 2021 11:36:06,109 [MANDATORY]  - [AIS]             Successfully loaded the descriptor at /C:/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/servers/AIS-DV91/stage/AIS_DV91/app/JDERestProxy.war/WEB-INF/classes/com/oracle/e1/jdemf/mbeans-descriptors.xml 
29 márc. 2021 11:36:16,022 [MANDATORY]  - [AIS]             Shutting down Quartz Scheduler 
29 márc. 2021 11:36:16,129 [MANDATORY]  - [AIS]             Session Cleanup Thread Stopped 
29 márc. 2021 11:36:16,136 [MANDATORY]  - [AIS]             Session Manager Instance: 1488520710 
29 márc. 2021 11:36:16,164 [MANDATORY]  - [AIS]             Successfully Un-Registered session_manager MBean from the MBean Server 
29 márc. 2021 11:36:16,165 [MANDATORY]  - [AIS]             Successfully Un-Registered sys_info MBean from the MBean Server 
29 márc. 2021 11:36:16,166 [MANDATORY]  - [AIS]             Successfully Un-Registered saw_log_manager MBean from the MBean Server 
29 márc. 2021 11:36:16,171 [MANDATORY]  - [AIS]             Successfully Un-Registered runtime_config MBean from the MBean Server 
29 márc. 2021 11:41:30,450 [MANDATORY]  - [AIS]             Initiating EnterpriseOne startup using configuration location (default_path) as 'C:\jde_home\SCFHA\targets\AIS_DV91\config'. 
29 márc. 2021 11:41:31,732 [MANDATORY]  - [AIS]             Successfully set the targetType to restserver 
29 márc. 2021 11:41:31,762 [MANDATORY]  - [AIS]             Successfully Initialize the management infrastructure com.oracle.e1.rest.E1RestSysInfoBean@43390857 
29 márc. 2021 11:41:31,773 [MANDATORY]  - [AIS]             Successfully register the runtime metric used by SCF to handle the logging configuration dynamically com.jdedwards.base.logging.saw.JdeSawManager@183ce96 
29 márc. 2021 11:41:31,773 [MANDATORY]  - [AIS]             Successfully got the Management Server Singleton and Registered sys_info and saw_log_manager 
29 márc. 2021 11:41:31,773 [MANDATORY]  - [AIS]             Obtained resUrl1 to be /C:/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/servers/AIS-DV91/stage/AIS_DV91/app/JDERestProxy.war/WEB-INF/classes/com/oracle/e1/rest/mbeans-descriptors.xml 
29 márc. 2021 11:41:31,774 [MANDATORY]  - [AIS]             Obtained resUrl2 to be /C:/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/servers/AIS-DV91/stage/AIS_DV91/app/JDERestProxy.war/WEB-INF/classes/com/oracle/e1/jdemf/mbeans-descriptors.xml 
29 márc. 2021 11:41:31,782 [MANDATORY]  - [AIS]             Successfully loaded the descriptor at /C:/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/servers/AIS-DV91/stage/AIS_DV91/app/JDERestProxy.war/WEB-INF/classes/com/oracle/e1/rest/mbeans-descriptors.xml 
29 márc. 2021 11:41:31,788 [MANDATORY]  - [AIS]             Successfully loaded the descriptor at /C:/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/servers/AIS-DV91/stage/AIS_DV91/app/JDERestProxy.war/WEB-INF/classes/com/oracle/e1/jdemf/mbeans-descriptors.xml 
29 márc. 2021 11:44:53,650 [MANDATORY]  - [AIS]             Session Manager Instance: 442236803 
29 márc. 2021 12:07:44,853 [SEVERE] JDE - [AIS]             E1RestUtils jasFormServiceCall JAS ERROR OUTPUT: {"errors":[{"TITLE":"JAS_MSG431: Fetch serialized object failed. Please contact your system administrator.","DESC":"COULD NOT LOAD FORM: P55TRM10_W55TRM10G"},{"TITLE":"JAS_MSG431: Fetch serialized object failed. Please contact your system administrator.","DESC":"COULD NOT LOAD FORM: P55TRM10_W55TRM10G"}]} 
29 márc. 2021 14:17:44,333 [SEVERE] JDE - [AIS]             E1RestTokenServer jasAuthentication JAS ERROR OUTPUT: inputParams  INPUT PARAMS: jde-JDV920-*ALL-http://192.168.0.87:91 Exception Occurred http://192.168.0.87:91/jde/FormServiceRequest java.io.FileNotFoundException: http://192.168.0.87:91/jde/FormServiceRequest
29 márc. 2021 14:17:44,335 [WARN  ] JDE - [AIS]             E1RestUtils: loginErrorResponse() - Failure to login error response json com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (String)"<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Draft//EN"><HTML><HEAD><TITLE>Error 404--Not Found</TITLE></HEAD><BODY bgcolor="white"><FONT FACE=Helvetica><BR CLEAR=all><TABLE border=0 cellspacing=5><TR><TD><BR CLEAR=all><FONT FACE="Helvetica" COLOR="black" SIZE="3"><H2>Error 404--Not Found</H2></FONT></TD></TR></TABLE><TABLE border=0 width=100% cellpadding=10><TR><TD VALIGN=top WIDTH=100% BGCOLOR=white><FONT FACE="Courier New"><FONT FACE="Helvetica" SIZE="3"><H3>From RFC 2068 <i>Hypertext Transfer"[truncated 645 chars]; line: 1, column: 2]
30 márc. 2021 10:32:13,790 [WARN  ] JDE - [AIS]             E1ResttoJASServer: Exception Processing Data Service java.lang.Exception: Invalid Token: Please Request a New Token
